Detect non zero status in bin/adado and report to user.

diff --git a/bin/adado b/bin/adado
--- a/bin/adado
+++ b/bin/adado
@@ -63,5 +63,10 @@ ant -q -Dada.home="$ADA_HOME" \
        -f "$AllTargets" $*
 
 # Check for status: 0 = OK, 1 = Something went wrong!
+adaAntStatus="$?"
+if [ $adaAntStatus -ne 0 ]; then
+  echo "An error has occurred. Check build.out for more information."
+fi
+
 exit
 
